### ISSUE TITLE
Hi, need help...What's the env variable: HOME? and I can't run the test on my windows 11

### ISSUE THREAD

**Issue by qzd1989** [cafercangundogdu/tesseract-rs#1]
I set the HOME to ""
```rust
//build.rs:14
let home_dir = "";
```
Then run cargo test:
```powershell
PS C:\Users\kiwi\rust\tesseract-rs> cargo test
Compiling tesseract-rs v0.1.18 (C:\Users\kiwi\rust\tesseract-rs)
The following warnings were emitted during compilation:

warning: tesseract-rs@0.1.18: custom_out_dir: "C:\\Users\\kiwi\\AppData\\Roaming\\tesseract-rs"

error: failed to run custom build command for `tesseract-rs v0.1.18 (C:\Users\kiwi\rust\tesseract-rs)`

Caused by:
  process didn't exit successfully: `C:\Users\kiwi\rust\tesseract-rs\target\debug\build\tesseract-rs-a962e8cad8d9438d\build-script-build` (exit code: 101)
  --- stdout
  cargo:warning=custom_out_dir: "C:\\Users\\kiwi\\AppData\\Roaming\\tesseract-rs"
  Building leptonica library
  CMAKE_TOOLCHAIN_FILE_aarch64-pc-windows-msvc = None
  CMAKE_TOOLCHAIN_FILE_aarch64_pc_windows_msvc = None
  HOST_CMAKE_TOOLCHAIN_FILE = None
  CMAKE_TOOLCHAIN_FILE = None
  CMAKE_GENERATOR_aarch64-pc-windows-msvc = None
  CMAKE_GENERATOR_aarch64_pc_windows_msvc = None
  HOST_CMAKE_GENERATOR = None
  CMAKE_GENERATOR = None
  CMAKE_PREFIX_PATH_aarch64-pc-windows-msvc = None
  CMAKE_PREFIX_PATH_aarch64_pc_windows_msvc = None
  HOST_CMAKE_PREFIX_PATH = None
  CMAKE_PREFIX_PATH = None
  CMAKE_aarch64-pc-windows-msvc = None
  CMAKE_aarch64_pc_windows_msvc = None
  HOST_CMAKE = None
  CMAKE = None
  running: "cmake" "C:\\Users\\kiwi\\AppData\\Roaming\\tesseract-rs\\third_party\\leptonica" "-G" "Visual Studio 17 2022" "-Thost=x64" "-AARM64" "-DCMAKE_BUILD_TYPE=Release" "-DBUILD_PROG=OFF" "-DBUILD_SHARED_LIBS=OFF" "-DENABLE_ZLIB=OFF" "-DENABLE_PNG=OFF" "-DENABLE_JPEG=OFF" "-DENABLE_TIFF=OFF" "-DENABLE_WEBP=OFF" "-DENABLE_OPENJPEG=OFF" "-DENABLE_GIF=OFF" "-DNO_CONSOLE_IO=ON" "-DCMAKE_CXX_FLAGS=/EHsc /MP -DUSE_STD_NAMESPACE " "-DMINIMUM_SEVERITY=L_SEVERITY_NONE" "-DSW_BUILD=OFF" "-DHAVE_LIBZ=0" "-DENABLE_LTO=OFF" "-DCMAKE_INSTALL_PREFIX=C:\\Users\\kiwi\\AppData\\Roaming\\tesseract-rs\\leptonica" "-DCMAKE_CXX_FLAGS_RELEASE=/MD" "-DCMAKE_CXX_FLAGS_DEBUG=/MDd" "-DCMAKE_POSITION_INDEPENDENT_CODE=ON" "-DCMAKE_C_FLAGS= -nologo -MD -Brepro" "-DCMAKE_C_FLAGS_RELEASE= -nologo -MD -Brepro" "-DCMAKE_ASM_FLAGS= -nologo -MD -Brepro" "-DCMAKE_ASM_FLAGS_RELEASE= -nologo -MD -Brepro"
  --
  -- General configuration for Leptonica
  -- --------------------------------------------------------
  -- Build type: Release
  -- Compiler: MSVC
  -- C compiler options:
      -nologo -MD -Brepro /MP
  -- Linker options: /machine:ARM64

  -- Install directory: C:/Users/kiwi/AppData/Roaming/tesseract-rs/leptonica
  --
  -- Build with sw [SW_BUILD]: OFF
  -- Build utility programs [BUILD_PROG]: OFF
  -- Used ZLIB library:
  -- Used PNG library:
  -- Used JPEG library:
  -- Used OpenJPEG library:
  -- Used TIFF library:
  -- Used GIF library:
  -- Used WebP library:
  -- --------------------------------------------------------
  --
  -- Configuring done (0.1s)
  -- Generating done (0.2s)

  --- stderr
  CMake Deprecation Warning at CMakeLists.txt:11 (cmake_minimum_required):
    Compatibility with CMake < 3.10 will be removed from a future version of
    CMake.

    Update the VERSION argument <min> value or use a ...<max> suffix to tell
    CMake that the project does not need compatibility with older versions.


  CMAKE_BUILD_TYPE = Release
  CMake Error in CMakeLists.txt:
    Evaluation file to be written multiple times with different content.  This
    is generally caused by the content evaluating the configuration type,
    language, or location of object files:

     C:/Users/kiwi/rust/tesseract-rs/target/debug/build/tesseract-rs-87b523a08096b90b/out/build/lept.pc


  CMake Error in CMakeLists.txt:
    Evaluation file to be written multiple times with different content.  This
    is generally caused by the content evaluating the configuration type,
    language, or location of object files:

     C:/Users/kiwi/rust/tesseract-rs/target/debug/build/tesseract-rs-87b523a08096b90b/out/build/lept.pc


  CMake Error in CMakeLists.txt:
    Evaluation file to be written multiple times with different content.  This
    is generally caused by the content evaluating the configuration type,
    language, or location of object files:

     C:/Users/kiwi/rust/tesseract-rs/target/debug/build/tesseract-rs-87b523a08096b90b/out/build/lept.pc


  CMake Error in CMakeLists.txt:
    Evaluation file to be written multiple times with different content.  This
    is generally caused by the content evaluating the configuration type,
    language, or location of object files:

     C:/Users/kiwi/rust/tesseract-rs/target/debug/build/tesseract-rs-87b523a08096b90b/out/build/lept.pc


  CMake Error in CMakeLists.txt:
    Evaluation file to be written multiple times with different content.  This
    is generally caused by the content evaluating the configuration type,
    language, or location of object files:

     C:/Users/kiwi/rust/tesseract-rs/target/debug/build/tesseract-rs-87b523a08096b90b/out/build/lept.pc


  CMake Error in CMakeLists.txt:
    Evaluation file to be written multiple times with different content.  This
    is generally caused by the content evaluating the configuration type,
    language, or location of object files:

     C:/Users/kiwi/rust/tesseract-rs/target/debug/build/tesseract-rs-87b523a08096b90b/out/build/lept.pc


  CMake Generate step failed.  Build files cannot be regenerated correctly.
  thread 'main' panicked at C:\Users\kiwi\.cargo\registry\src\index.crates.io-6f17d22bba15001f\cmake-0.1.51\src/lib.rs:1100:5:

  command did not execute successfully, got: exit code: 1

  build script failed, must exit now
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
versions:
```powershell
PS C:\Users\kiwi\rust\tesseract-rs> cmake --version
cmake version 3.31.0
CMake suite maintained and supported by Kitware (kitware.com/cmake).
PS C:\Users\kiwi\rust\tesseract-rs> rustup --version
rustup 1.27.1 (54dd3d00f 2024-04-24)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.82.0 (f6e511eec 2024-10-15)`
PS C:\Users\kiwi\rust\tesseract-rs> cargo --version
cargo 1.82.0 (8f40fc59f 2024-08-21)
PS C:\Users\kiwi\rust\tesseract-rs> rustc --version
rustc 1.82.0 (f6e511eec 2024-10-15)
```
![system](https://github.com/user-attachments/assets/9fab8d98-130f-4aa9-92c0-7219e239dfea)

**Comment by qzd1989** [comment]
I also try to buid on github workflow and get the same error.

I set the HOME to ""
```rust
//build.rs:14
let home_dir = "";
```

```yml
//.github/workflows/build.yml
name: windows-build

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: choco installing
        run: |
          choco install cmake -y
          choco install llvm -y

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install sccache
        run: cargo install sccache

      - name: Build
        run: cargo build
```

build error log:

```powershell
cargo build
  shell: C:\Program Files\PowerShell\7\pwsh.EXE -command ". '{0}'"
  
    Updating crates.io index
 Downloading crates ...
  Downloaded bumpalo v3.16.0
  Downloaded sync_wrapper v1.0.1
  Downloaded zeroize_derive v1.4.2
  Downloaded lzma-rs v0.3.0
  Downloaded zopfli v0.8.1
  Downloaded unicode-bidi v0.3.17
  Downloaded zip v2.2.0
  Downloaded url v2.5.2
  Downloaded unicode-normalization v0.1.24
  Downloaded h2 v0.4.6
  Downloaded hyper v1.4.1
  Downloaded reqwest v0.12.8
  Downloaded hashbrown v0.15.0
  Downloaded flate2 v1.0.34
  Downloaded serde v1.0.210
  Downloaded proc-macro2 v1.0.87
  Downloaded syn v2.0.79
  Downloaded idna v0.5.0
  Downloaded hyper-util v0.1.9
  Downloaded unicode-ident v1.0.13
  Downloaded rustls v0.23.14
  Downloaded schannel v0.1.26
  Downloaded rustls-pki-types v1.9.0
  Downloaded pin-project-lite v0.2.14
  Downloaded cc v1.1.30
  Downloaded thiserror-impl v1.0.64
  Downloaded thiserror v1.0.64
  Downloaded simd-adler32 v0.3.7
  Downloaded lockfree-object-pool v0.1.6
  Downloaded itoa v1.0.11
  Downloaded glob v0.3.1
  Downloaded bzip2-sys v0.1.11+1.0.8
  Downloaded deflate64 v0.1.9
  Downloaded crc-catalog v2.4.0
  Downloaded crc v3.2.1
  Downloaded cpufeatures v0.2.14
  Downloaded cmake v0.1.51
  Downloaded bzip2 v0.4.4
  Downloaded bytes v1.7.2
  Downloaded libc v0.2.161
  Downloaded tokio v1.40.0
  Downloaded encoding_rs v0.8.34
   Compiling windows_x86_64_msvc v0.52.6
   Compiling proc-macro2 v1.0.87
   Compiling unicode-ident v1.0.13
   Compiling version_check v0.9.5
   Compiling typenum v1.17.0
   Compiling windows-targets v0.52.6
   Compiling jobserver v0.1.32
   Compiling shlex v1.3.0
   Compiling generic-array v0.14.7
   Compiling cc v1.1.30
   Compiling cfg-if v1.0.0
   Compiling bytes v1.7.2
   Compiling quote v1.0.37
   Compiling syn v2.0.79
   Compiling pkg-config v0.3.31
   Compiling pin-project-lite v0.2.14
   Compiling windows-sys v0.52.0
   Compiling futures-core v0.3.31
   Compiling autocfg v1.4.0
   Compiling futures-sink v0.3.31
   Compiling slab v0.4.9
   Compiling itoa v1.0.11
   Compiling once_cell v1.20.2
   Compiling fnv v1.0.7
   Compiling http v1.1.0
   Compiling crypto-common v0.1.6
   Compiling equivalent v1.0.1
   Compiling hashbrown v0.15.0
   Compiling memchr v2.7.4
   Compiling indexmap v2.6.0
   Compiling tracing-core v0.1.32
   Compiling socket2 v0.5.7
   Compiling mio v1.0.2
   Compiling zstd-sys v2.0.13+zstd.1.5.6
   Compiling futures-task v0.3.31
   Compiling futures-io v0.3.31
   Compiling pin-utils v0.1.0
   Compiling tokio v1.40.0
   Compiling byteorder v1.5.0
   Compiling httparse v1.9.5
   Compiling futures-util v0.3.31
   Compiling zerocopy-derive v0.7.35
   Compiling tracing v0.1.40
   Compiling http-body v1.0.1
   Compiling block-buffer v0.10.4
   Compiling windows-sys v0.59.0
   Compiling atomic-waker v1.1.2
   Compiling try-lock v0.2.5
   Compiling subtle v2.6.1
   Compiling libc v0.2.161
   Compiling tokio-util v0.7.12
   Compiling tinyvec_macros v0.1.1
   Compiling native-tls v0.2.12
   Compiling tinyvec v1.8.0
   Compiling h2 v0.4.6
   Compiling digest v0.10.7
   Compiling want v0.3.1
   Compiling zerocopy v0.7.35
   Compiling futures-channel v0.3.31
   Compiling bzip2-sys v0.1.11+1.0.8
   Compiling getrandom v0.2.15
   Compiling smallvec v1.13.2
   Compiling serde v1.0.210
   Compiling schannel v0.1.26
   Compiling zstd-safe v7.2.1
   Compiling percent-encoding v2.3.1
   Compiling rand_core v0.6.4
   Compiling form_urlencoded v1.2.1
   Compiling ppv-lite86 v0.2.20
   Compiling unicode-normalization v0.1.24
   Compiling hyper v1.4.1
   Compiling inout v0.1.3
   Compiling crc32fast v1.4.2
   Compiling windows-result v0.2.0
   Compiling adler2 v2.0.0
   Compiling crc-catalog v2.4.0
   Compiling tower-service v0.3.3
   Compiling unicode-bidi v0.3.17
   Compiling cpufeatures v0.2.14
   Compiling thiserror v1.0.64
   Compiling log v0.4.22
   Compiling powerfmt v0.2.0
   Compiling idna v0.5.0
   Compiling deranged v0.3.11
   Compiling hyper-util v0.1.9
   Compiling crc v3.2.1
   Compiling miniz_oxide v0.8.0
   Compiling windows-strings v0.1.0
   Compiling cipher v0.4.4
   Compiling rand_chacha v0.3.1
   Compiling tokio-native-tls v0.3.1
   Compiling hmac v0.12.1
   Compiling http-body-util v0.1.2
   Compiling zeroize_derive v1.4.2
   Compiling thiserror-impl v1.0.64
   Compiling zip v2.2.0
   Compiling rustls-pki-types v1.9.0
   Compiling simd-adler32 v0.3.7
   Compiling bumpalo v3.16.0
   Compiling ryu v1.0.18
   Compiling num-conv v0.1.0
   Compiling time-core v0.1.2
   Compiling lockfree-object-pool v0.1.6
   Compiling time v0.3.36
   Compiling bzip2 v0.4.4
   Compiling zopfli v0.8.1
   Compiling rustls-pemfile v2.2.0
   Compiling zeroize v1.8.1
   Compiling hyper-tls v0.6.0
   Compiling rand v0.8.5
   Compiling pbkdf2 v0.12.2
   Compiling zstd v0.13.2
   Compiling flate2 v1.0.34
   Compiling serde_urlencoded v0.7.1
   Compiling aes v0.8.4
   Compiling windows-registry v0.2.0
   Compiling lzma-rs v0.3.0
   Compiling url v2.5.2
   Compiling sha1 v0.10.6
   Compiling displaydoc v0.2.5
   Compiling sync_wrapper v1.0.1
   Compiling encoding_rs v0.8.34
   Compiling deflate64 v0.1.9
   Compiling ipnet v2.10.1
   Compiling mime v0.3.17
   Compiling constant_time_eq v0.3.1
   Compiling base64 v0.22.1
   Compiling cmake v0.1.51
   Compiling glob v0.3.1
   Compiling reqwest v0.12.8
   Compiling tesseract-rs v0.1.18 (D:\a\tesseract-rs\tesseract-rs)
The following warnings were emitted during compilation:
warning: tesseract-rs@0.1.18: custom_out_dir: "C:\\Users\\runneradmin\\AppData\\Roaming\\tesseract-rs"
error: failed to run custom build command for `tesseract-rs v0.1.18 (D:\a\tesseract-rs\tesseract-rs)`
Caused by:
  process didn't exit successfully: `D:\a\tesseract-rs\tesseract-rs\target\debug\build\tesseract-rs-25ac001cb622b8b8\build-script-build` (exit code: 101)
  --- stdout
  cargo:warning=custom_out_dir: "C:\\Users\\runneradmin\\AppData\\Roaming\\tesseract-rs"
  Building leptonica library
  CMAKE_TOOLCHAIN_FILE_x86_64-pc-windows-msvc = None
  CMAKE_TOOLCHAIN_FILE_x86_64_pc_windows_msvc = None
  HOST_CMAKE_TOOLCHAIN_FILE = None
  CMAKE_TOOLCHAIN_FILE = None
  CMAKE_GENERATOR_x86_64-pc-windows-msvc = None
  CMAKE_GENERATOR_x86_64_pc_windows_msvc = None
  HOST_CMAKE_GENERATOR = None
  CMAKE_GENERATOR = None
  CMAKE_PREFIX_PATH_x86_64-pc-windows-msvc = None
  CMAKE_PREFIX_PATH_x86_64_pc_windows_msvc = None
  HOST_CMAKE_PREFIX_PATH = None
  CMAKE_PREFIX_PATH = None
  CMAKE_x86_64-pc-windows-msvc = None
  CMAKE_x86_64_pc_windows_msvc = None
  HOST_CMAKE = None
  CMAKE = None
  running: "cmake" "C:\\Users\\runneradmin\\AppData\\Roaming\\tesseract-rs\\third_party\\leptonica" "-G" "Visual Studio 17 2022" "-Thost=x64" "-Ax64" "-DCMAKE_BUILD_TYPE=Release" "-DBUILD_PROG=OFF" "-DBUILD_SHARED_LIBS=OFF" "-DENABLE_ZLIB=OFF" "-DENABLE_PNG=OFF" "-DENABLE_JPEG=OFF" "-DENABLE_TIFF=OFF" "-DENABLE_WEBP=OFF" "-DENABLE_OPENJPEG=OFF" "-DENABLE_GIF=OFF" "-DNO_CONSOLE_IO=ON" "-DCMAKE_CXX_FLAGS=/EHsc /MP -DUSE_STD_NAMESPACE " "-DMINIMUM_SEVERITY=L_SEVERITY_NONE" "-DSW_BUILD=OFF" "-DHAVE_LIBZ=0" "-DENABLE_LTO=OFF" "-DCMAKE_INSTALL_PREFIX=C:\\Users\\runneradmin\\AppData\\Roaming\\tesseract-rs\\leptonica" "-DCMAKE_CXX_FLAGS_RELEASE=/MD" "-DCMAKE_CXX_FLAGS_DEBUG=/MDd" "-DCMAKE_POSITION_INDEPENDENT_CODE=ON" "-DCMAKE_C_FLAGS= -nologo -MD -Brepro" "-DCMAKE_C_FLAGS_RELEASE= -nologo -MD -Brepro" "-DCMAKE_ASM_FLAGS= -nologo -MD -Brepro" "-DCMAKE_ASM_FLAGS_RELEASE= -nologo -MD -Brepro"
  -- The C compiler identification is MSVC 19.42.34433.0
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.42.34433/bin/Hostx64/x64/cl.exe - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Looking for sin in m
  -- Looking for sin in m - not found
  -- Looking for include file dlfcn.h
  -- Looking for include file dlfcn.h - not found
  -- Looking for include file inttypes.h
  -- Looking for include file inttypes.h - found
  -- Looking for include file memory.h
  -- Looking for include file memory.h - found
  -- Looking for include file stdint.h
  -- Looking for include file stdint.h - found
  -- Looking for include file stdlib.h
  -- Looking for include file stdlib.h - found
  -- Looking for include file strings.h
  -- Looking for include file strings.h - not found
  -- Looking for include file string.h
  -- Looking for include file string.h - found
  -- Looking for include file sys/stat.h
  -- Looking for include file sys/stat.h - found
  -- Looking for include file sys/types.h
  -- Looking for include file sys/types.h - found
  -- Looking for include file unistd.h
  -- Looking for include file unistd.h - not found
  -- Looking for fmemopen
  -- Looking for fmemopen - not found
  -- Looking for fstatat
  -- Looking for fstatat - not found
  -- 
  -- General configuration for Leptonica 
  -- --------------------------------------------------------
  -- Build type: Release
  -- Compiler: MSVC
  -- C compiler options:
      -nologo -MD -Brepro /MP
  -- Linker options: /machine:x64
    
  -- Install directory: C:/Users/runneradmin/AppData/Roaming/tesseract-rs/leptonica
  -- 
  -- Build with sw [SW_BUILD]: OFF
  -- Build utility programs [BUILD_PROG]: OFF
  -- Used ZLIB library: 
  -- Used PNG library:  
  -- Used JPEG library: 
  -- Used OpenJPEG library: 
  -- Used TIFF library: 
  -- Used GIF library:  
  -- Used WebP library: 
  -- --------------------------------------------------------
  -- 
  -- Configuring done (26.5s)
  -- Generating done (0.0s)
  --- stderr
  CMake Deprecation Warning at CMakeLists.txt:11 (cmake_minimum_required):
    Compatibility with CMake < 3.10 will be removed from a future version of
    CMake.
    Update the VERSION argument <min> value or use a ...<max> suffix to tell
    CMake that the project does not need compatibility with older versions.
  CMAKE_BUILD_TYPE = Release
  CMake Error in CMakeLists.txt:
    Evaluation file to be written multiple times with different content.  This
    is generally caused by the content evaluating the configuration type,
    language, or location of object files:
     D:/a/tesseract-rs/tesseract-rs/target/debug/build/tesseract-rs-bf5d3e530ed1e0a5/out/build/lept.pc
  CMake Error in CMakeLists.txt:
    Evaluation file to be written multiple times with different content.  This
    is generally caused by the content evaluating the configuration type,
    language, or location of object files:
     D:/a/tesseract-rs/tesseract-rs/target/debug/build/tesseract-rs-bf5d3e530ed1e0a5/out/build/lept.pc
  CMake Error in CMakeLists.txt:
    Evaluation file to be written multiple times with different content.  This
    is generally caused by the content evaluating the configuration type,
    language, or location of object files:
     D:/a/tesseract-rs/tesseract-rs/target/debug/build/tesseract-rs-bf5d3e530ed1e0a5/out/build/lept.pc
  CMake Error in CMakeLists.txt:
    Evaluation file to be written multiple times with different content.  This
    is generally caused by the content evaluating the configuration type,
    language, or location of object files:
     D:/a/tesseract-rs/tesseract-rs/target/debug/build/tesseract-rs-bf5d3e530ed1e0a5/out/build/lept.pc
  CMake Error in CMakeLists.txt:
    Evaluation file to be written multiple times with different content.  This
    is generally caused by the content evaluating the configuration type,
    language, or location of object files:
     D:/a/tesseract-rs/tesseract-rs/target/debug/build/tesseract-rs-bf5d3e530ed1e0a5/out/build/lept.pc
  CMake Error in CMakeLists.txt:
    Evaluation file to be written multiple times with different content.  This
    is generally caused by the content evaluating the configuration type,
    language, or location of object files:
     D:/a/tesseract-rs/tesseract-rs/target/debug/build/tesseract-rs-bf5d3e530ed1e0a5/out/build/lept.pc
  CMake Warning:
    Manually-specified variables were not used by the project:
      CMAKE_ASM_FLAGS
      CMAKE_ASM_FLAGS_RELEASE
      CMAKE_CXX_FLAGS
      CMAKE_CXX_FLAGS_DEBUG
      CMAKE_CXX_FLAGS_RELEASE
      ENABLE_LTO
      MINIMUM_SEVERITY
      NO_CONSOLE_IO
  CMake Generate step failed.  Build files cannot be regenerated correctly.
  thread 'main' panicked at C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\cmake-0.1.51\src/lib.rs:1100:5:
  command did not execute successfully, got: exit code: 1
  build script failed, must exit now
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Error: Process completed with exit code 1.
```
